In [34]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [23]:
import os
import pandas as pd

Jogos = pd.read_csv('WorldCupMatches.csv')
Jogadores = pd.read_csv('WorldCupPlayers.csv')
Tabela = pd.read_csv('WorldCups.csv')

Jogos.head()

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
0,1930.0,13 Jul 1930 - 15:00,Group 1,Pocitos,Montevideo,France,4.0,1.0,Mexico,,4444.0,3.0,0.0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201.0,1096.0,FRA,MEX
1,1930.0,13 Jul 1930 - 15:00,Group 4,Parque Central,Montevideo,USA,3.0,0.0,Belgium,,18346.0,2.0,0.0,MACIAS Jose (ARG),MATEUCCI Francisco (URU),WARNKEN Alberto (CHI),201.0,1090.0,USA,BEL
2,1930.0,14 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,2.0,1.0,Brazil,,24059.0,2.0,0.0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201.0,1093.0,YUG,BRA
3,1930.0,14 Jul 1930 - 14:50,Group 3,Pocitos,Montevideo,Romania,3.0,1.0,Peru,,2549.0,1.0,0.0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201.0,1098.0,ROU,PER
4,1930.0,15 Jul 1930 - 16:00,Group 1,Parque Central,Montevideo,Argentina,1.0,0.0,France,,23409.0,0.0,0.0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201.0,1085.0,ARG,FRA

In [21]:
Jogadores.head()

,RoundID,MatchID,Team Initials,Coach Name,Line-up,Shirt Number,Player Name,Position,Event
0,201,1096,FRA,CAUDRON Raoul (FRA),S,0,Alex THEPOT,GK,NaN
1,201,1096,MEX,LUQUE Juan (MEX),S,0,Oscar BONFIGLIO,GK,NaN
2,201,1096,FRA,CAUDRON Raoul (FRA),S,0,Marcel LANGILLER,NaN,G40'
3,201,1096,MEX,LUQUE Juan (MEX),S,0,Juan CARRENO,NaN,G70'
4,201,1096,FRA,CAUDRON Raoul (FRA),S,0,Ernest LIBERATI,NaN,NaN

In [24]:
Tabela.head()

,Year,Country,Winner,Runners-Up,Third,Fourth,GoalsScored,QualifiedTeams,MatchesPlayed,Attendance
0,1930,Uruguay,Uruguay,Argentina,USA,Yugoslavia,70,13,18,590.549
1,1934,Italy,Italy,Czechoslovakia,Germany,Austria,70,16,17,363.000
2,1938,France,Italy,Hungary,Brazil,Sweden,84,15,18,375.700
3,1950,Brazil,Uruguay,Brazil,Sweden,Spain,88,13,22,1.045.246
4,1954,Switzerland,Germany FR,Hungary,Austria,Uruguay,140,16,26,768.607

In [25]:
Tabela.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Year            20 non-null     int64
 1   Country         20 non-null     object
 2   Winner          20 non-null     object
 3   Runners-Up      20 non-null     object
 4   Third           20 non-null     object
 5   Fourth          20 non-null     object
 6   GoalsScored     20 non-null     int64
 7   QualifiedTeams  20 non-null     int64
 8   MatchesPlayed   20 non-null     int64
 9   Attendance      20 non-null     object
dtypes: int64(4), object(6)
memory usage: 1.7+ KB

In [38]:
Tabela.describe()

              Year  GoalsScored  QualifiedTeams  MatchesPlayed
count    20.000000    20.000000       20.000000      20.000000
mean   1974.800000   118.950000       21.250000      41.800000
std      25.582889    32.972836        7.268352      17.218717
min    1930.000000    70.000000       13.000000      17.000000
25%    1957.000000    89.000000       16.000000      30.500000
50%    1976.000000   120.500000       16.000000      38.000000
75%    1995.000000   145.250000       26.000000      55.000000
max    2014.000000   171.000000       32.000000      64.000000

In [102]:


# Filtrar as linhas onde o jogador contém "Arantes"
pele_gols = Jogadores[Jogadores['Player Name'].str.contains('Arantes', case=False, na=False)].copy()

# Adicionar uma coluna para contar os gols
pele_gols.loc[:, 'Gol Count'] = pele_gols['Event'].str.count('G')

# Somar o número total de gols de Pelé
total_gols_pele = pele_gols['Gol Count'].sum()

# Imprimir o resultado
print(f"Total de gols marcados por Pelé: {total_gols_pele}")

Total de gols marcados por Pelé: 12.0

In [160]:


# Filtrar as linhas onde o jogador contém "Arantes"
pele_gols = Jogadores[Jogadores['Player Name'].str.contains('Arantes', case=False, na=False)].copy()

# Adicionar uma coluna para contar os gols
pele_gols.loc[:, 'Gol Count'] = pele_gols['Event'].str.count('G')

# Filtrar os jogos onde Pelé fez gols
jogos_pele = jogos[jogos['MatchID'].isin(pele_gols['MatchID'])]

# Mesclar os DataFrames para obter informações adicionais
pele_gols_info = pd.merge(pele_gols, jogos_pele[['MatchID', 'Stadium', 'City']], on='MatchID')

# Obter os estádios e cidades onde Pelé fez gols
estadios_cidades_pele = pele_gols_info[['Stadium', 'City']].drop_duplicates()

# Imprimir os estádios e cidades onde Pelé fez gols sem exibir o índice
print("Estádios e cidades onde Pelé fez gols:")
print(estadios_cidades_pele.to_string(index=False))

Estádios e cidades onde Pelé fez gols:
          Stadium               City
    Rimnersvallen          Udevalla
       Nya Ullevi        Gothenburg
  Rasunda Stadium             Solna
Estadio Sausalito      Vina Del Mar
         Nacional Santiago De Chile
    Goodison Park         Liverpool
          Jalisco       Guadalajara
   Estadio Azteca       Mexico City

In [161]:

# Filtrar as linhas onde o jogador contém "Arantes"
pele_gols = Jogadores[Jogadores['Player Name'].str.contains('Arantes', case=False, na=False)].copy()

# Adicionar uma coluna para contar os gols
pele_gols['Gol Count'] = pele_gols['Event'].str.count('G')

# Filtrar os jogos onde Pelé fez gols
jogos_pele = jogos[jogos['MatchID'].isin(pele_gols['MatchID'])]

# Mesclar os DataFrames para obter informações adicionais
pele_gols_info = pd.merge(pele_gols, jogos_pele[['MatchID', 'Stadium', 'City']], left_on='MatchID', right_on='MatchID', how='left')

# Criar um DataFrame para contar cada ocorrência de 'G' individualmente
gol_count_df = pele_gols_info['Event'].str.extractall('(G\d+)').reset_index()
gol_count_df.columns = ['match_index', 'event_index', 'Gol Event']

# Se existirem linhas sem correspondência, adicione valores padrão para 'Stadium' e 'City'
gol_count_df[['Stadium', 'City']] = pele_gols_info[['Stadium', 'City']].fillna('Desconhecido')

# Agrupar e contar os gols por estádio e cidade
gol_count_by_stadium_city = gol_count_df.groupby(['Stadium', 'City']).size().reset_index(name='Gol Count')

# Imprimir os estádios, cidades e contagem de gols onde Pelé fez gols sem exibir o índice
print("Estádios, cidades e contagem de gols onde Pelé fez gols:")
print(gol_count_by_stadium_city.to_string(index=False))

Estádios, cidades e contagem de gols onde Pelé fez gols:
          Stadium               City  Gol Count
Estadio Sausalito      Vina Del Mar           4
         Nacional Santiago De Chile           2
       Nya Ullevi        Gothenburg           3
  Rasunda Stadium             Solna           2
    Rimnersvallen          Udevalla           1

In [162]:
import pandas as pd
from tabulate import tabulate

# Leitura dos DataFrames Jogos, Jogadores e Tabela
jogos = pd.read_csv('WorldCupMatches.csv', encoding='latin1')
jogadores = pd.read_csv('WorldCupPlayers.csv', encoding='latin1')
tabela = pd.read_csv('WorldCups.csv', encoding='latin1')

# Filtrar as linhas onde o jogador contém "Arantes"
pele_gols = jogadores[jogadores['Player Name'].str.contains('Arantes', case=False, na=False)].copy()

# Adicionar uma coluna para contar os gols
pele_gols['Gol Count'] = pele_gols['Event'].str.count('G')

# Filtrar os jogos onde Pelé fez gols
jogos_pele = jogos[jogos['MatchID'].isin(pele_gols['MatchID'])]

# Mesclar os DataFrames para obter informações adicionais
pele_gols_info = pd.merge(pele_gols, jogos_pele[['MatchID', 'Stadium', 'City', 'Attendance']], left_on='MatchID', right_on='MatchID', how='left')

# Criar um DataFrame para contar cada ocorrência de 'G' individualmente
gol_count_df = pele_gols_info['Event'].str.extractall('(G\d+)').reset_index()
gol_count_df.columns = ['match_index', 'event_index', 'Gol Event']

# Se existirem linhas sem correspondência, adicione valores padrão para 'Stadium', 'City', e 'Attendance'
gol_count_df[['Stadium', 'City', 'Attendance']] = pele_gols_info[['Stadium', 'City', 'Attendance']].fillna('Desconhecido')

# Agrupar e contar os gols por estádio, cidade e somar a assistência
gol_count_by_stadium_city = gol_count_df.groupby(['Stadium', 'City'])[['Gol Event', 'Attendance']].agg({'Gol Event': 'count', 'Attendance': 'sum'}).reset_index()

# Criar um DataFrame organizado
resultado_df = pd.DataFrame({
    'Estádio': gol_count_by_stadium_city['Stadium'],
    'Cidade': gol_count_by_stadium_city['City'],
    'Contagem de Gols': gol_count_by_stadium_city['Gol Event'],
    'Total de Pessoas': gol_count_by_stadium_city['Attendance']
})
# Adicionar linhas para a contagem total de gols e o total de pessoas
total_gols = resultado_df['Contagem de Gols'].sum()
total_pessoas = resultado_df['Total de Pessoas'].sum()

resultado_df.loc[len(resultado_df)] = ['Total', '', total_gols, total_pessoas]

# Imprimir a tabela organizada sem os totais
print("Estádios, cidades, contagem de gols e total de pessoas que viram os gols de Pelé:")
print(tabulate(resultado_df.iloc[:-1, :], headers='keys', tablefmt='psql', showindex=False))

# Adicionar linha horizontal antes da última linha com totais
print("\n" + "-"*50)
print(tabulate(resultado_df.tail(1), headers='keys', tablefmt='psql', showindex=False))

Estádios, cidades, contagem de gols e total de pessoas que viram os gols de Pelé:
+-------------------+-------------------+--------------------+--------------------+
| Estádio           | Cidade            |   Contagem de Gols |   Total de Pessoas |
|-------------------+-------------------+--------------------+--------------------|
| Estadio Sausalito | Vina Del Mar      |                  4 |              61838 |
| Nacional          | Santiago De Chile |                  2 |             145273 |
| Nya Ullevi        | Gothenburg        |                  3 |             117746 |
| Rasunda Stadium   | Solna             |                  2 |              76837 |
| Rimnersvallen     | Udevalla          |                  1 |              17788 |
+-------------------+-------------------+--------------------+--------------------+

--------------------------------------------------
+-----------+----------+--------------------+--------------------+
| Estádio   | Cidade   |   Contagem de Gols |   Total de Pessoas |
|-----------+----------+--------------------+--------------------|
| Total     |          |                 12 |             419482 |
+-----------+----------+--------------------+--------------------+